### ISSUE TITLE
T440p unable to go to sleep

### ISSUE THREAD

**Issue by swatchie-1** [swanux/t440p#2]
Hi Swanux, when i put the laptop to sleep, it blinks once then lights up again and wakes up by itself. The laptop also gets warm and instantly turns on the screen when i press any key. Doesn't look like the sleep is working. Do you encounter it?
Running v1.5

**Comment by swanux** [comment]
Hi Swatchie,
As far as I know it worked for me, but tested it again now just to be sure: for me it works the following way
1. I put it to sleep either from the OS or by closing the lid
2. screen instantly goes black
3. after around 20s the i on the back and the power indicator start to blink and I can only wake it up by opening the lid / pressing the power button (as expected)

However, I have an idea: if I press any key or sth between step 2 and 3 (in that 20s) it wakes up. Maybe you just should wait a bit longer?
Also note, that I'm not docked during the test, and no external devices are attached.
Do you have some extra information in case waiting isn't working?

**Comment by swatchie-1** [comment]
Hi Swanux, thanks for your reply. I was trying out Sniki's opencore and then i booted yours using a usb and the problem occured. Maybe i need to reset nvram?

Also when docked, are you able to sleep? I tried sniki's and i'm not able to sleep while docked. But i'm able to sleep it if i remove the laptop from dock.

**Comment by swanux** [comment]
Hi Swatchie,
I've tested it when docked (of course no external displays, as it'd have caused reboot) and it works properly.
Regarding the nvram, I don't think that there might be a connection, but it's not impossible.
Anyway, tomorrow I'll investigate the issue, as I might have an idea.

**Comment by swanux** [comment]
@swatchie-1 I've made some changes to the EFI, so you can try whether it works or not. (For me it works just like before, so I'll rely on your tests) The EFIs are under `Versions` in the repo.
If it doesn't work, you can try to add [this](https://github.com/acidanthera/HibernationFixup) kext to your EFI (BTW for me it just made sleep even slower)
If it still doesn't work, then you can try the `Fixing sleep & Hibernate` part from [here](https://github.com/jloisel/t440p/blob/master/permission-T440P.sh)

**Comment by swatchie-1** [comment]
Hi swanux, thanks for your effort. I tried your airport version because i'm using a native airport card too. 
It still wakes up by itself when i put it to sleep while docked. I will try clover and see if there's any difference.

**Comment by swanux** [comment]
Hi Swatchie, I really don't know what could be the problem then. We have the same hardware so it should work. For me, with clover (from @jloisel), sleep also works. The only difference is that when it wakes up from sleep it's instantly usable. With OC I always have ~1.5s delay before I can see the password which I type. (Anyway OC is still in alpha) I'm curious whether it works for you with clover or not.

**Comment by swatchie-1** [comment]
Hi Swanux, thanks for the reply. I'm now using @jloisel's clover. It's running well here. It can now sleep (but takes longer to sleep) while docked. 
It's also faster for an external display to show up compared to OC. in OC, it takes about 10 secs to show the screen in an external monitor. In Clover it only takes about 5 secs.

For Audio applealc, I'm using the ALC3232 of layout-id 55. So I need to manually switch sound between Internal Speakers and Line Out when using the Dock and when removing it.  

Other than that, all looks fine for the moment.

**Comment by swanux** [comment]
Hi Swatchie, I'm glad it works for you. I hope OC 0.6 will bring some improvements.
Also I'm wondering if anyone else has similar problems. And it's strange that it works differently on same hardware..

EDIT: Regarding AppleALC, maybe you can mix the to EFIs to have something working, and use my SoundFix (as it's not dependent on OC)

**Comment by swatchie-1** [comment]
Hi Swanux, I'm back to using your EFI again since I have time on a Sunday to experiment. I've discovered the issue why my T440P can't sleep while docked. It's because of the USBPorts.kext.

1) I used your USBPorts.kext. Bluetooth is working but cannot sleep while docked.

2) I used Jloisel's USBPorts.kext (old version) and it can sleep while docked. But Bluetooth is not working.

I'm using the native airport card BCM943224PCIEBT2.

Do you know what needs to be changed to get the bluetooth and "sleep while docked" working normally?

here are screenshots.

![jlosel usbportskext](https://user-images.githubusercontent.com/40285586/89115341-eb4dbc80-d4b9-11ea-80c2-4b3dea0332e2.png)
![swanux usbportskext](https://user-images.githubusercontent.com/40285586/89115344-ef79da00-d4b9-11ea-9162-f17bc585e895.png)

**Comment by swatchie-1** [comment]
Hi, i got it fixed. Solution is to change the dock, brcm, integrated camera to Internal instead of USB3.

Thanks alot.

**Comment by swanux** [comment]
@swatchie-1 Thank you for providing your solution! Just a quick question: which serial number are you using? (iMac something or MacBookPro11,1 or 11,2)

**Comment by swatchie-1** [comment]
The same serial like yours macbookpro11,2

**Comment by swanux** [comment]
Okay, thanks. Then I have no idea why it didn't work for you by default. Anyway, I'll place a link in README to this issu in case anyone has the same problem.

**Comment by swatchie-1** [comment]
Im using an i7-4702mq though. Don’t think that affects. 
I broke my fingerprint flat ribbon cable while installing the native airport card. Now fixing it at a shop :)

**Comment by swanux** [comment]
Probably it doesn't affect anything, but good to know anyway.
Yeah, nearly I did the same, haha Good luck with it!
