### ISSUE TITLE
Unable to boot system uptime error

### ISSUE THREAD

**Issue by Azure-Orit** [swanux/t440p#3]
Mac OS Catalina
Stock T440p
[opencore-2020-08-02-023937.txt](https://github.com/swanux/t440p/files/5011561/opencore-2020-08-02-023937.txt)
![20200801_234152](https://user-images.githubusercontent.com/63315512/89114413-6c716900-d452-11ea-80c6-f8ca07fe5b3f.jpg)
system boots normally on clover, log and final picture of the panic attached

**Comment by swatchie-1** [comment]
Why don't you try to clean NVRam. also make sure you copy and paste the OC and Boot folder completely on your laptop's EFI folder.

**Comment by Azure-Orit** [comment]
tried it already, same results

**Comment by swanux** [comment]
@isa-pp I have a question and an idea.
Question: What is your BIOS version? Also, is it first boot, from installer?
Idea: Try with clover from @jloisel

**Comment by Azure-Orit** [comment]
Turns out the problem is that my system was already dirty, full of kexts. After a clean install on a separate volume everything is working well even my wifi dongle and bluetooth driver

**Comment by swanux** [comment]
Glad to hear that!
