### ISSUE TITLE
Problem with Airport network card

### ISSUE THREAD

**Issue by purpose-pending** [swanux/t440p#7]
I've been using previous version or this opencore build (airport version) fine. Yesterday updated opencore to latest version - everything worked fine. Tried updating Catalina to Big Sur afterwards - had some problems with AirportNetworkCard EFI version - install would fail, so switched to USBTethering EFI and upgrade went fine. But after updating and switching EFI back to AirportNetworkCard one -  WiFi doesn't work. It's probably Big Sur related, since it was fine on Catalina... Any advice?

**Comment by swanux** [comment]
Thank you for your feedback! Currently I'm using my config with Big Sur and Airport card and both Bluetooth and WiFi work fine for me. So it should be fine. I have two ideas:

- The difference may be that I didn't update from Catalina, but did a clean install with Big Sur instead.
- The only difference between USBTethering and AirportNetworkCard is that AirportNetworkCard has AirportBrcmFixup.kext, while USBTethering has HoRNDIS.kext.

Taking these into consideration it's either a problem with AirportBrcmFixup.kext (but it works for me, so probably not), or with the system itself. You can try older versions of the kext, or reinstalling the system (by the way, with big OS updates - not just on macOS - I'd always recommend a clean install, as things can get messy sometimes).

**Comment by purpose-pending** [comment]
Thanks for reply! Yeah, if it works for you - something probably must be messed up on my end. Gonna try to clean install on spare SSD, to check if Wi-Fi will work on that system.

**Comment by swanux** [comment]
No problem! I'm looking forward to the results.

**Comment by purpose-pending** [comment]
Well I tried a whole lot of things- for some reason couldn't manage to get WiFi working after all. Found other working EFI and went with it: https://github.com/lighterEB/ThinkPad-T440p 
No idea why this one wasn't working, but at least things are working fine.
